src/activity_feed/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import ActivityFeedListView


app_name = 'activity_feed'

urlpatterns = [
    path('', login_required(ActivityFeedListView.as_view()), name='activity_feed'),
]

src/cart/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CartListView, CartCreateView, CartUpdateView

app_name = 'cart'

urlpatterns = [
    path('', login_required(CartListView.as_view()), name='cart'),
    path('create/', login_required(CartCreateView.as_view()), name='cart-create-view'),
    path('update/', login_required(CartUpdateView.as_view()), name='cart-update-view'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('activity-feed/', include('activity_feed.urls')),
    path('cart/', include('cart.urls')),
    path('charts/', include('charts.urls')),
    path('checkout/', include('checkout.urls')),
    path('contact/', include('contact.urls')),
    path('comments/', include('comments.urls')),
    path('profiles/', include('profiles.urls')),
    path('tickets/', include('tickets.urls')),
]

src/tickets/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import TicketListView, TicketDetailView, TicketCreateView, TicketUpdateView

app_name = 'tickets'

urlpatterns = [
    path('bugs/', login_required(TicketListView.as_view()), name='bugs'),
    path('features/', login_required(TicketListView.as_view()), name='features'),
    path('<int:id>/<slug:slug>/details/', login_required(TicketDetailView.as_view()), name='ticket-detail-view'),
    path('<str:issue>/create/', login_required(TicketCreateView.as_view()), name='ticket-create-view'),
    path('<int:id>/<slug:slug>/update/', login_required(TicketUpdateView.as_view()), name='ticket-update-view'),
    path('api/', include('tickets.api.urls'), name='tickets.api.urls'),
]

src/activity_feed/views.py
from django.views.generic import ListView
from tickets.models import Ticket
from comments.models import Comment
from checkout.models import Order
from profiles.models import Profile
from itertools import chain


class ActivityFeedListView(ListView):
    """
    Gather an object list of the most recent actions by users,
    present as two separate tabs, current user and other users.
    """
    template_name = 'activity_feed/feed.html'
    extra_context = {}

    def get_queryset(self):
        user = self.request.user

        try:
            # call the model managers to query their models
            tickets_list = Ticket.objects.get_latest(user)
            comments_list = Comment.objects.get_latest(user)
            order_list = Order.objects.get_latest(user)
            profiles_list = Profile.objects.get_latest(user)

            # chain together all object lists to return a single object list
            queryset_chain = chain(tickets_list, comments_list, order_list, profiles_list)

            # sort the queryset by created on date to be on top
            queryset = sorted(queryset_chain, key=lambda instance: instance.created_on, reverse=True)
            return queryset

        # if there's a problem return empty queryset
        except LookupError:
            return Profile.objects.none()

src/activity_feed/templates/activity_feed/feed.html
{% extends '../base/base.html' %}
{% load static %}
{% load class_name %}
{% block head_title %}Activity Feed{% endblock %}
{% block content %}

	<h1 class="callout">Activity Feed</h1>
	<div id="activity-feed" class="ui container">

		<!-- Tab Menu -->
		<div class="ui tabular menu">
			<div class="right menu">
				<a class="item active" data-tab="tab-recent-feed">Recent Activity Feed</a>
				<a class="item" data-tab="tab-profile-feed">My Profile Feed</a>
			</div>
		</div>

		<!-- activity feed for other users action only -->
		<div class="ui tab active" data-tab="tab-recent-feed">
			<div class="ui small feed">
				{% for object in object_list %}
					{% with object|class_name as model %}

						<!-- create ticket action -->
						{% if model == 'Ticket' and object.username != request.user.username %}
							<div class="event">
								<div class="label">
									<img src="{{ object.user.profile.avatar }}" alt="avatar image">
								</div>
								<div class="content">
									<div class="summary">
										<span class="user">
											{{ object.user.username|title }}
										</span> Created a new {{ object.issue|title }}
										<div class="date">
											{{ object.created_on|timesince }}
										</div>
									</div>
									<div class="meta">
										<a class="like" href="{% url 'tickets:ticket-detail-view' id=object.id slug=object.slug %}">
											<i class="terminal alternate black icon"></i> <span class="code">#{{ object.id }}</span> {{ object.title }}
										</a>
									</div>
								</div>
							</div>
							<div class="ui divider"></div>

						<!-- create comment action -->
						{% elif  model == 'Comment' and object.username != request.user.username %}
							<div class="event">
								<div class="label">
									<img src="{{ object.user.profile.avatar }}" alt="avatar image">
								</div>
								<div class="content">
									<div class="summary">
										<span class="user">
											{{ object.user.username|title }}
										</span> Made a Comment on a Ticket
										<div class="date">
											{{ object.updated_on|timesince }}
										</div>
									</div>
									<div class="meta">
										<a class="like" href="{% url 'tickets:ticket-detail-view' id=object.ticket.id slug=object.ticket.slug %}">
											<i class="comment alternate blue icon"></i> <span class="code">#{{ object.ticket.id }}</span> {{ object.text }}
										</a>
									</div>
								</div>
							</div>
							<div class="ui divider"></div>

						<!-- purchased votes action -->
						{% elif model == 'Order' and object.user != request.user %}
							<div class="event">
								<div class="label">
									<img src="{{ object.user.profile.avatar }}" alt="avatar image">
								</div>
								<div class="content">
									<div class="summary">
										<span class="user">
											{{ object.user.username|title }}
										</span> Supported a Ticket
										<div class="date">
											{{ object.date|timesince }}
										</div>
									</div>
									<div class="meta">
										<span class="like">
											<i class="certificate icon orange"></i> Paid for {{ object.votes }} Vote(s), Nice one!
										</span>
									</div>
								</div>
							</div>
							<div class="ui divider"></div>

							<!-- new user joined action -->
							{% elif model == 'Profile' and object.user != request.user %}
							<div class="event">
								<div class="label">
									<img src="{{ object.user.profile.avatar }}" alt="avatar image">
								</div>
								<div class="content">
									<div class="summary">
										<span class="user">
											{{ object.user.username|title }}
										</span> Just Joined  - Welcome Them!
										<div class="date">
											{{ object.created_on|timesince }}
										</div>
									</div>
									<div class="meta">
										<span class="like">
											<i class="thumbs up green icon"></i> Thanks for Joining {{ object.user.username|title }}
										</span>
									</div>
								</div>
							</div>
							<div class="ui divider"></div>
						{% endif %}
					{% endwith %}
				{% endfor %}
			</div>
		</div>

		<!-- current user (my profile) actions only -->
		<div class="ui tab" data-tab="tab-profile-feed">
			<div class="ui small feed">
				{% for object in object_list %}
					{% with object|class_name as model %}

						<!-- create ticket action -->
						{% if model == 'Ticket' and object.username == request.user.username %}
							<div class="event">
									<div class="label">
										<img src="{{ object.user.profile.avatar }}" alt="avatar image">
									</div>
									<div class="content">
										<div class="summary">
											<span class="user">
												{{ object.user.username|title }}
											</span> Created a new {{ object.issue|title }}
											<div class="date">
												{{ object.created_on|timesince }}
											</div>
										</div>
										<div class="meta">
											<a class="like" href="{% url 'tickets:ticket-detail-view' id=object.id slug=object.slug %}">
												<i class="terminal alternate black icon"></i>  <span class="code">#{{ object.id }}</span> {{ object.title|title }}
											</a>
										</div>
									</div>
								</div>
								<div class="ui divider"></div>

						<!-- create comment action -->
						{% elif  model == 'Comment' and object.username == request.user.username %}
							<div class="event">
								<div class="label">
									<img src="{{ object.user.profile.avatar }}" alt="avatar image">
								</div>
								<div class="content">
									<div class="summary">
										<span class="user">
											{{ object.user.username|title }}
										</span> Made a comment on a Ticket
										<div class="date">
											{{ object.updated_on|timesince }}
										</div>
									</div>
									<div class="meta">
										<a class="like" href="{% url 'tickets:ticket-detail-view' id=object.ticket.id slug=object.ticket.slug %}">
											<i class="comment alternate blue icon"></i> <span class="code">#{{ object.ticket.id }}</span> {{ object.text }}
										</a>
									</div>
								</div>
							</div>
							<div class="ui divider"></div>

						<!-- purchase votes action -->
						{% elif model == 'Order' and object.user == request.user %}
							<div class="event">
								<div class="label">
									<img src="{{ object.user.profile.avatar }}" alt="avatar image">
								</div>
								<div class="content">
									<div class="summary">
										<span class="user">
											{{ object.user.username|title }}
										</span> Supported a Ticket
										<div class="date">
											{{ object.date|timesince }}
										</div>
									</div>
									<div class="meta">
										<span class="like">
											<i class="certificate icon orange"></i> Paid for {{ object.votes }} Vote(s), Nice one!
										</span>
									</div>
								</div>
							</div>
							<div class="ui divider"></div>

							<!-- user joined action -->
							{% elif model == 'Profile' and object.user == request.user %}
							<div class="event">
								<div class="label">
									<img src="{{ object.user.profile.avatar }}" alt="avatar image">
								</div>
								<div class="content">
									<div class="summary">
										<span class="user">
											{{ object.user.username|title }}
										</span> You Just Joined!
										<div class="date">
											{{ object.created_on|timesince }}
										</div>
									</div>
									<div class="meta">
										<span class="like">
											<i class="thumbs up green icon"></i> Thanks for Joining {{ object.user.username|title }}
										</span>
									</div>
								</div>
							</div>
							<div class="ui divider"></div>
						{% endif %}
					{% endwith %}
				{% endfor %}
			</div>
		</div>

		<!-- end of page refresh button -->
		<div class="ui stacked segment mt1">
			<h4 class="ui header">
				<i class="plug icon"></i>
				<span class="content dib">
					<a href="{% url 'activity_feed:activity_feed' %}">Refresh Content ...</a>
				</span>
			</h4>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script>
        $('.tabular.menu .item').tab();
	</script>
{% endblock %}