src/cart/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CartListView, CartCreateView, CartUpdateView

app_name = 'cart'

urlpatterns = [
    path('', login_required(CartListView.as_view()), name='cart'),
    path('create/', login_required(CartCreateView.as_view()), name='cart-create-view'),
    path('update/', login_required(CartUpdateView.as_view()), name='cart-update-view'),
]

src/charts/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

app_name = 'charts'

urlpatterns = [
    path('', login_required(TemplateView.as_view(template_name='charts/charts.html')), name='charts'),
    path('api/data/', include('charts.api.urls'),  name='charts.api.urls'),
]

src/contact/urls.py
from django.urls import path
from .views import ContactCreateView

app_name = 'contact'

urlpatterns = [
    path('', ContactCreateView.as_view(), name='contact'),
]

src/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import IndexView

app_name = 'pages'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('faq/', TemplateView.as_view(template_name='pages/faq.html'), name='faq'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('activity-feed/', include('activity_feed.urls')),
    path('cart/', include('cart.urls')),
    path('charts/', include('charts.urls')),
    path('checkout/', include('checkout.urls')),
    path('contact/', include('contact.urls')),
    path('comments/', include('comments.urls')),
    path('profiles/', include('profiles.urls')),
    path('tickets/', include('tickets.urls')),
]

src/tickets/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import TicketListView, TicketDetailView, TicketCreateView, TicketUpdateView

app_name = 'tickets'

urlpatterns = [
    path('bugs/', login_required(TicketListView.as_view()), name='bugs'),
    path('features/', login_required(TicketListView.as_view()), name='features'),
    path('<int:id>/<slug:slug>/details/', login_required(TicketDetailView.as_view()), name='ticket-detail-view'),
    path('<str:issue>/create/', login_required(TicketCreateView.as_view()), name='ticket-create-view'),
    path('<int:id>/<slug:slug>/update/', login_required(TicketUpdateView.as_view()), name='ticket-update-view'),
    path('api/', include('tickets.api.urls'), name='tickets.api.urls'),
]

src/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- meta -->
	{% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Submit your bugs for free or have us work on your projects next upcoming feature. What are we working on next?. Up-vote tickets to see them realised sooner. Log in to get started!">
    <meta name="author" content="Sean Murphy">
    <title>{% block head_title %}{% endblock %}</title>

	<!-- styles -->
	<link rel="shortcut icon" type="image/png" href="{% static 'img/logos/bug-icon.png' %}" sizes="128x128">
	<link rel="stylesheet" href="{% static 'css/beard.min.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
	<link rel="stylesheet" href="{% static 'css/base.css' %}" />
	{% block css %}{% endblock %}
</head>
<body class="pushable">

	<!-- nav-bar-mobile -->
	{% include './nav-sidebar.html' %}

	<div class="pusher">
		<!-- header -->
		<header id="header">
			<div class="ui menu">{% include './navbar.html' %}</div>
			<div class="ui fixed menu transition hidden">{% include './navbar.html' %}</div>
		</header>

		<!-- main content -->
		<main id="main">
			{% block content %}{% endblock %}
		</main>

		<!-- to top button -->
		{% include './to-top-button.html' %}

		<!-- busy-loader -->
		{% include './busy-loader.html' %}

		<!-- footer -->
		<footer>
			{% include './footer.html' %}
		</footer>
	</div>

	<!-- scripts -->
	<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
	<script type="application/javascript" src="{% static 'js/base.js' %}"></script>
	<script type="application/javascript" src="{% static 'js/moment.min.js' %}"></script>
	<script type="application/javascript" src="{% static 'js/csrf-token-cookie.js' %}"></script>
	{% block javascript %}{% endblock %}
</body>
</html>

src/templates/base/busy-loader.html
<div id="busy-loader">
	<div class="spinner">
		<div class="double-bounce1"></div>
		<div class="double-bounce2"></div>
	</div>
</div>

src/templates/base/footer.html
<div id="footer-container" class="ui inverted vertical footer segment">
	<div class="ui container">
		<div class="ui stackable inverted divided equal height stackable grid">

			<!-- quick links -->
			<div class="three wide column">
				<h4 class="ui inverted header">Quick Links</h4>
				<div class="ui inverted link list">
					<a href="{% url 'pages:index' %}" class="item">Home</a>
					<a href="{% url 'pages:faq' %}" class="item">FAQ's</a>
					<a href="{% url 'contact:contact' %}" class="item">Contact Us</a>
					{% if not user.is_authenticated %}
						<a href="{% url 'account_login' %}" class="item">Login</a>
					{% else %}
						<a href="{% url 'account_logout' %}" class="item">Logout</a>
					{% endif %}
				</div>
			</div>
			<div class="three wide column">
				<h4 class="ui inverted header">Services</h4>
				<div class="ui inverted link list">
					<a href="{% url 'tickets:bugs' %}" class="item">Squash those Bugs</a>
					<a href="{% url 'tickets:features' %}" class="item">Get Features Realised</a>
					<a href="{% url 'charts:charts' %}" class="item">Current Charts Lists</a>
					<a href="https://stripe.com/ie" rel="noopener" target="_blank" class="item">Secure Stripe Payments</a>
				</div>
			</div>

			<!-- social links -->
			<div class="seven wide column">
				<h4 class="ui inverted header">
					<a class="ui item tcg40 :tcg10" href="{% url 'pages:index' %}">
						<span id="logo-title-first" >Issue</span>
						<span id="logo-title-last">Tracker</span>
					</a>
				</h4>
				<p>We're available on Social Media too, get it touch and see what we're up to!</p>
				<a href="https://github.com/nazarja" rel="noopener" target="_blank"  class="ui github grey small button mt1">
				  <i class="github icon"></i>
				  Github
				</a>
				<a href="https://www.seanmurphy.dev" rel="noopener" target="_blank"  class="ui green small button mt1">
					<i class="code icon"></i>
					seanmurphy.dev
				</a>
				<a href="https://www.linkedin.com/in/sean-murphy-dev" rel="noopener" target="_blank" class="ui linkedin small button mt1">
					<i class="linkedin icon"></i>
					LinkedIn
				</a>
			</div>
		</div>

		<!-- footer credits -->
		<div class="mt4">
			<p>Made with <i class="code icon"></i> and <i class="coffee icon"></i> by  <a href="https://seanmurphy.dev" rel="noopener" target="_blank">Sean_Murphy</a>  &copy; 2019</p>
		</div>
	</div>
</div>

src/templates/base/nav-sidebar.html
{% load static %}

<div class="ui vertical inverted sidebar menu left" style="">
	<a id="logo-title-mobile" class="ui item" href="{% url 'pages:index' %}">
		<span id="logo-title-first" >Issue</span>
		<span id="logo-title-last">Tracker</span>
	</a>

	{% if not user.is_authenticated  %}

		<!-- only viewable on home page -->
		{% if request.path == '/' %}
			<a class="item" href="#pricing">Pricing</a>
			<a class="item" href="#how-it-works">How it works?</a>
		{% endif %}

		<!-- always viewable -->
		<a class="item" href="{% url 'pages:faq' %}">FAQ's</a>
		<a class="item" href="{% url 'contact:contact' %}">Contact</a>
		<a class="item header" href="{% url 'account_login' %}">Login</a>
		<a class="item header" href="{% url 'account_signup' %}">Sign up</a>

	<!-- user logged in -->
	{% else %}

		<!-- username and avatar -->
		<span class="item">Hi, {{ request.user.username|title }} <img id="side-bar-avatar" src="{{ request.session.avatar }}" alt="avatar"></span>

		<!-- cart and cart count -->
		<a class="item" href="{% url 'cart:cart' %}">Cart
			<div class="cart-item-count ui label green">
				{{ cart_count }}
			</div>
		</a>

		<!-- rest of menu -->
		<a class="item" href="{% url 'activity_feed:activity_feed' %}">Activity Feed</a>
		<a class="item" href="{% url 'tickets:bugs' %}">Bugs</a>
		<a class="item" href="{% url 'tickets:features' %}">Features</a>
		<a class="item" href="{% url 'charts:charts' %}">Charts</a>
		<span class="item">Help &amp; Support <i class="angle down icon"></i></span>
		<a class="item" href="{% url 'pages:faq' %}">FAQ's</a>
		<a class="item" href="{% url 'contact:contact' %}">Contact Us</a>
		<a class="item" href="{% url 'account_set_password' %}">Change Password</a>
		<a class="item" href="{% url 'profiles:change_avatar' %}">Change Avatar Picture</a>
		<a class="item" href="{% url 'account_logout' %}">Logout</a>
	{% endif %}
</div>

src/templates/base/navbar.html
{% load static  %}
{% load socialaccount %}
<nav>
	<div class="ui container">

		<!-- mobile nav-bar-->
		<div id="nav-bar-small" class="ui secondary inverted menu">
			<a class="toc item">
				<i class="sidebar icon"></i>
			</a>

			<!-- logo -->
			<a id="logo-title" class="ui item" href="{% url 'pages:index' %}">
				<span id="logo-title-first" >Issue</span>
				<span id="logo-title-last">Tracker</span>
			</a>

			<!-- right hand side menu -->
			<div class="right menu">

				<!-- not logged in -->
				{% if not user.is_authenticated %}
					<a class="item header" href="{% url 'account_login' %}">Login</a>
					<a class="item header" href="{% url 'account_signup' %}">Sign up</a>

				<!-- logged in -->
				{% else %}

					<!-- cart icon and cart count -->
					<a class="item cart-popup" href="{% url 'cart:cart' %}" data-content="View Cart">
						<i class="shop icon"></i>
						<div class="cart-item-count ui label green">{{ cart_count }}</div>
					</a>

					<!-- username and avatar -->
					<div id="username-small" class="item">
						<span class="avatar-label ui black label">
							<img id="avatar-1" class="avatar-label-image avatar image" src="{{ request.session.avatar }}" alt="avatar">
							Hi, {{ user.username|title }}
						</span>
					</div>
					<a id="logout-small" class="item header" href="{% url 'account_logout' %}">Logout</a>
				{% endif %}
			</div>
		</div>

		<!-- desktop nav-bar -->
		<div id="nav-bar-large" class="ui secondary inverted menu">
			<div class="item">
				<a href="{% url 'pages:index' %}">
					<img height="50" width="50" src="{% static 'img/logos/logo.png' %}" alt="bug logo">
				</a>
			</div>

			<!-- not logged in -->
			{% if not user.is_authenticated  %}
				<a class="ui item" href="{% url 'pages:index' %}">
					<span id="logo-title-first" >Issue</span>
					<span id="logo-title-last">Tracker</span>
				</a>

				<!-- only visible on home page -->
				{% if request.path == '/' %}
					<a class="item" href="#pricing">Pricing</a>
					<a class="item" href="#how-it-works">How it Works?</a>
				{% endif %}

			<!-- logged in -->
			{% else %}
				<a class="item" href="{% url 'tickets:bugs' %}">Bugs</a>
				<a class="item" href="{% url 'tickets:features' %}">Features</a>
				<a class="item" href="{% url 'charts:charts' %}">Charts</a>
				<a class="item" href="{% url 'activity_feed:activity_feed' %}">Activity Feed</a>
			{% endif %}

			<!-- right hand side menu -->
			<div class="right menu">

				<!-- logged in -->
				{% if user.is_authenticated %}

					<!-- cart icon and cart count -->
					<a class="item cart-popup" href="{% url 'cart:cart' %}" data-content="View Cart">
						<i class="shop icon"></i>
						<div class="cart-item-count ui label green">
							{{ cart_count }}
						</div>
					</a>

				<!-- not logged in -->
				{% endif %}
				<div class="ui dropdown item">
					Help &amp; Support
					<i class="dropdown icon"></i>
					<div class="menu inverted">
						<a class="item" href="{% url 'pages:faq' %}">FAQ's</a>
						<a class="item" href="{% url 'contact:contact' %}">Contact Us</a>

						<!-- logged in -->
						{% if user.is_authenticated  %}
							<a class="item" href="{% url 'account_set_password' %}">Change Password</a>
							<a class="item" href="{% url 'profiles:change_avatar' %}">Change Avatar Picture</a>
						{% endif %}
					</div>
				</div>

				<!-- logged in -->
				{% if user.is_authenticated %}
					<div id="username-large" class="item">
						<span class="avatar-label ui black label">
							<img id="avatar-2" class="avatar-label-image  avatar image" src="{{ request.session.avatar }}" alt="avatar">
							Hi, {{ user.username|title }}
						</span>
					</div>
					<a class="item header" href="{% url 'account_logout' %}">Logout</a>

				<!-- not logged in -->
				{% else %}
					<div class="ui buttons">
						<div class="nav-bar-button">
							<a class="ui standard inverted button" href="{% url 'account_login' %}">Login</a>
						</div>
						<div class="item">
							<div id="nav-bar-or" class="or"></div>
						</div>
						<div class="nav-bar-button">
							<a id="nav-bar-sign-up-button" class="ui green inverted button" href="{% url 'account_signup' %}">Sign up</a>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
</nav>

src/templates/base/to-top-button.html
<a href="#header" id="to-top-btn" class="circular ui green icon button">
  <i class="angle up icon"></i>
</a>