src/cart/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CartListView, CartCreateView, CartUpdateView

app_name = 'cart'

urlpatterns = [
    path('', login_required(CartListView.as_view()), name='cart'),
    path('create/', login_required(CartCreateView.as_view()), name='cart-create-view'),
    path('update/', login_required(CartUpdateView.as_view()), name='cart-update-view'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import handler404, handler500


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('activity-feed/', include('activity_feed.urls')),
    path('cart/', include('cart.urls')),
    path('charts/', include('charts.urls')),
    path('checkout/', include('checkout.urls')),
    path('contact/', include('contact.urls')),
    path('comments/', include('comments.urls')),
    path('profiles/', include('profiles.urls')),
    path('tickets/', include('tickets.urls')),
]

src/tickets/api/urls.py
from django.urls import path
from .views import TicketListAPIView, TicketDeleteAPIView, TicketVoteAPIView

urlpatterns = [
    path('list/', TicketListAPIView.as_view(), name='ticket-list-api'),
    path('<int:id>/delete/', TicketDeleteAPIView.as_view(), name='ticket-delete-api'),
    path('<int:id>/vote/', TicketVoteAPIView.as_view(), name='ticket-vote-api'),
]

src/tickets/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import TicketListView, TicketDetailView, TicketCreateView, TicketUpdateView

app_name = 'tickets'

urlpatterns = [
    path('bugs/', login_required(TicketListView.as_view()), name='bugs'),
    path('features/', login_required(TicketListView.as_view()), name='features'),
    path('<int:id>/<slug:slug>/details/', login_required(TicketDetailView.as_view()), name='ticket-detail-view'),
    path('<str:issue>/create/', login_required(TicketCreateView.as_view()), name='ticket-create-view'),
    path('<int:id>/<slug:slug>/update/', login_required(TicketUpdateView.as_view()), name='ticket-update-view'),
    path('api/', include('tickets.api.urls'), name='tickets.api.urls'),
]

src/tickets/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.utils.encoding import smart_text
from django.urls import reverse
from datetime import datetime


STATUS_CHOICES = (
    ('need help', 'need help'),
    ('in progress', 'in progress'),
    ('resolved', 'resolved'),
)

ISSUE_CHOICES = (
    ('bug', 'bug'),
    ('feature', 'feature')
)


class TicketManager(models.Manager):
    """
    model manager for activity feed,
    return queryset's for the user's and other user's ticket creation actions
    """
    def get_latest(self, query=None):
        """
        exclude the user from one queryset,
        include in a separate query to ensure we get current user results
        """
        all_queryset = self.get_queryset().exclude(user=query).order_by('-updated_on')[:5]
        user_queryset = self.get_queryset().filter(user=query).order_by('-updated_on')[:5][:5]

        # join together with a pipe to return as a single queryset
        return all_queryset | user_queryset


class Ticket(models.Model):
    """
    a ticket can be either a bug or a feature, a ticket is associated to its creator via a foreign key.
    a ticket can have many people that have voted for it. the tickets url will be its id and its title.
    a ticket must keep track of how many votes and money has been obtained.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, editable=False, on_delete=models.CASCADE)
    username = models.CharField(max_length=100, blank=False, null=True)
    avatar = models.CharField(max_length=100, blank=True, null=True, default='/static/img/avatars/tim.png')
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=100, blank=False, null=True)
    description = models.CharField(max_length=1000, blank=False, null=True)
    status = models.CharField(max_length=100, default='need help', choices=STATUS_CHOICES)
    votes = models.IntegerField(default=0)
    created_on = models.DateTimeField(default=datetime.now)
    updated_on = models.DateTimeField(auto_now=True)
    earned = models.IntegerField(default=0, null=True, blank=True)
    issue = models.CharField(max_length=100, blank=False, null=True, choices=ISSUE_CHOICES)
    slug = models.SlugField(max_length=100, null=True, blank=True)
    vote_profiles = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='vote_profiles_many')
    objects = TicketManager()

    def save(self, *args, **kwargs):
        """
        override save function, on save:
        slug field becomes a slugified version of the tickets title
        username is current users username and avatar assigned for easy access to it
        """
        self.slug = slugify(self.title)
        self.avatar = self.user.profile.avatar
        self.username = self.user.username
        super(Ticket, self).save(*args, **kwargs)

    def __str__(self):
        return smart_text(f'{self.issue}: No: {self.id} by {self.username} | {self.title}')

    def get_absolute_url(self):
        """
            depending on if a bug or feature is saved, the user will be returned to the
            bug or feature main page after submitting their ticket
        """
        return reverse(f'tickets:{self.issue}s')

src/tickets/forms.py
from django import forms
from .models import Ticket


class TicketForm(forms.ModelForm):
    """
    inherits from ticket modal to create a form,
    most fields are left out and fields saved on the view / serializer
    description field needs a custom textarea field
    """
    description = forms.CharField(max_length=2000, required=True, widget=forms.Textarea)

    class Meta:
        model = Ticket
        fields = [
            'title',
            'description',
            'status',
        ]

src/tickets/api/views.py
from rest_framework.generics import ListAPIView, DestroyAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import TicketListSerializer, TicketDeleteSerializer
from .permissions import IsOwnerOrReadOnly
from django.http import Http404
from django.db.models import Q
from tickets.models import Ticket


class TicketListAPIView(ListAPIView):
    """
    returns a ticket queryset based on a query, filter or pagination request
    """
    serializer_class = TicketListSerializer

    def get_queryset(self):
        # get query params needed for the lookup
        query = self.request.query_params.get('q', None)
        issue = self.request.query_params.get('issue', 'bug')
        order = self.request.query_params.get('order', '-updated_on')

        # filter choices
        if order in ['need help', 'in progress', 'resolved']:
            status = order

            # filter choices and query together
            if query is not None:
                return Ticket.objects.filter(
                    Q(title__icontains=query, issue=issue, status=status) | Q(description__icontains=query, issue=issue, status=status)
                ).order_by('-updated_on')

            # return only filtered choices
            return Ticket.objects.filter(issue=issue, status=status).order_by('-updated_on')

        # if a query is passed
        if query is not None:
            return Ticket.objects.filter(
                Q(title__icontains=query, issue=issue) | Q(description__icontains=query, issue=issue)
            ).order_by(order)

        # no query - no choices - generic order by
        return Ticket.objects.filter(issue=issue).order_by(order)


class TicketDeleteAPIView(DestroyAPIView):
    """
    deletes a ticket by the id field only if you are th owner
    """
    lookup_field = 'id'
    queryset = Ticket.objects.all()
    serializer_class = TicketDeleteSerializer
    permission_classes = [IsOwnerOrReadOnly]


class TicketVoteAPIView(APIView):
    """
    accepts a put request to increase a vote on a bug
    """
    def get_object(self, _id):
        """
        try get the ticket object, raise a 404 if it doesnt exist
        """
        try:
            return Ticket.objects.get(id=_id)
        except Ticket.DoesNotExist:
            raise Http404

    def put(self, request, id, format=None):
        """
        update the tickets vote field by one,
        add to user to the tickets manytomany field
        """
        instance = self.get_object(id)
        user = self.request.user

        #  if the user has already voted on the ticket, dont continue
        if user in instance.vote_profiles.all():
            return Response({'text': 'already voted for this', 'votes': instance.votes})

        # otherwise increase the votes and save the user
        else:
            instance.votes += 1
            instance.vote_profiles.add(user)
            instance.save()
            return Response({'text': 'ok', 'votes': instance.votes})

src/tickets/views.py
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Ticket
from .forms import TicketForm
from datetime import datetime


def bug_or_feature(self):
    """
    helper function to determine issue type is a bug or feature
    """
    return 'bug' if 'bug' in self.request.path else 'feature'


class TicketListView(ListView):
    """
    ticket list view, return first 8 tickets,
    counts all tickets to determine if pagination is allowed
    """
    template_name = 'tickets/ticket-list-view.html'
    paginate_by = 8
    extra_context = {}
    allow_empty = True

    def get_queryset(self):
        issue = bug_or_feature(self)
        self.extra_context['issue'] = issue
        self.extra_context['count'] = Ticket.objects.filter(issue=issue).order_by('-updated_on').count()
        return Ticket.objects.filter(issue=issue).order_by('-updated_on')


class TicketDetailView(DetailView):
    """
    renders the tickets details page, figuring out if the current user is the owner
    allows us to check we should show edit and delete controls
    """
    template_name = 'tickets/ticket-detail-view.html'
    extra_context = {'issue': 'issue details', 'already_voted': 'false'}

    def get_object(self, queryset=Ticket):
        # get first ticket with matching id and get the current user
        _id = self.kwargs.get('id')
        instance = Ticket.objects.filter(id=_id).first()
        user = self.request.user

        if instance:
            # dont allow user to vote twice on a bug
            if user in instance.vote_profiles.all():
                self.extra_context['already_voted'] = 'true'
            else:
                self.extra_context['already_voted'] = 'false'
            return instance
        else:
            raise Http404


class TicketCreateView(CreateView):
    """
    renders the create ticket view
    """
    model = Ticket
    form_class = TicketForm
    template_name = 'tickets/ticket-create-update-view.html'
    extra_context = {'issue': 'create new ticket', 'button_text': 'create', 'time': datetime.now()}

    def form_valid(self, form):
        """
        on valid form submit we must assign the current user to the ticket instance
        """
        form.instance.user = self.request.user
        form.instance.issue = bug_or_feature(self)
        return super(TicketCreateView, self).form_valid(form)


class TicketUpdateView(UpdateView):
    """
    renders the ticket update / preview view
    get first matching object, on form_valid, save the form.
    """
    form_class = TicketForm
    template_name = 'tickets/ticket-create-update-view.html'
    extra_context = {'issue': 'update ticket', 'button_text': 'update'}

    def get_object(self, queryset=Ticket):
        _id = self.kwargs.get('id')
        return get_object_or_404(Ticket, id=_id)

    def form_valid(self, form):
        return super().form_valid(form)

src/tickets/templates/tickets/bugs.html
{% extends '../base/base.html' %}
{% load static %}
{% block head_title %}Bugs{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'tickets/css/tickets.css' %}"/>{% endblock %}
{% block content %}
	<h1 class="callout">Bugs</h1>
	<div class="ui container">
	<ul>
	{% for bug in object_list %}
		<li>{{ bug.title }} - {{ bug.updated_on }}</li>
	{% empty %}
		<li>No bugs yet.</li>
	{% endfor %}
</ul>
	</div>
{% endblock %}

src/tickets/templates/tickets/ticket-create-update-view.html
{% extends '../base/base.html' %}
{% load static %}
{% block head_title %}{{ issue|title }}{% endblock %}
{% block css %}
	<link rel="stylesheet" href="{% static 'css/forms.css' %}"/>
	<link rel="stylesheet" href="{% static 'tickets/css/tickets.css' %}"/>
{% endblock %}
{% block content %}

	<h1 class="callout">{{ issue|title }}</h1>

	<!-- dynamic ticket preview partial -->
	<div class="ui container">
		{% include 'tickets/partials/ticket-details-preview-item.html' %}
	</div>

	<!-- divider -->
	<h3 class="ui container horizontal divider header mv3">
	  <i class="wpforms icon"></i> Preview
	</h3>

	<!-- characters left indicators -->
	<div id="chars-left-metadata" class="fwnormal tal mb1 ui container">
		<div class="title-chars-left dib">Title chars left: <span class="fwsemibold">100</span></div>
		<div class="description-chars-left dib pl1">Description chars left: <span class="fwsemibold">2000</span></div>
	</div>

	<!-- update form -->
	<div class="ui container tac middle aligned segment raised padded ma2 pt3">
		<form class="all-forms" method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="ui button submit green">{{ button_text|title }} Ticket</button>

			<!-- only if editing the ticket and the owner show delete button -->
			{% if request.user == object.user and  'update' in request.path %}
				<button id="ticket-delete-btn" class="ui button submit red">Delete Ticket</button>
			{% endif %}
		</form>
	</div>

	<!-- delete confirmation modal -->
	{% include 'tickets/partials/ticket-delete-item.html' %}
{% endblock %}

{% block javascript %}
	<script src="{%  static 'tickets/js/ticket-api.js' %}"></script>
	<script src="{%  static 'tickets/js/ticket-details-preview.js' %}"></script>
{% endblock %}

src/tickets/templates/tickets/ticket-detail-view.html
{% extends '../base/base.html' %}
{% load static %}
{% block head_title %}{{ issue|title }}{% endblock %}
{% block css %}
	<link rel="stylesheet" href="{% static 'tickets/css/tickets.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/forms.css' %}"/>
{% endblock %}
{% block content %}

	<h1 class="callout">{{ issue|title }}</h1>
	<div class="ui container">

		<!-- ticket details preview partial -->
		{% include 'tickets/partials/ticket-details-preview-item.html' %}

	    <!-- ticket owner controls -->
		{% if request.user == object.user %}
			<a href="{% url 'tickets:ticket-update-view' id=object.id slug=object.slug %}" class="ui button tiny submit green">Edit Issue</a>
			<button id="ticket-delete-btn" class="ui button tiny submit red">Delete Issue</button>
		{% else %}

			<!-- user voting controls-->
			{% if object.issue == 'bug' %}
				<p class="fwsemibold">Vote For This Issue:</p>
				{% if already_voted == 'true' %}
					<button class="ui button tiny" disabled>You have already voted for this</button>
				{% else %}
					<button id="ticket-vote-free" class="ui button tiny primary" data-id="{{ object.id }}">I have this too</button>
				{% endif %}

			<!-- purchase controls if its a feature -->
			{% elif object.issue == 'feature' %}
				<p class="fwsemibold">Support This Issue:</p>
				<button id="ticket-vote-single" class="ui button tiny primary mb1" data-id="{{ object.id }}">Single Vote - I Want This Too - &euro; 5.00</button>
				<button id="ticket-vote-double" class="ui button tiny green" data-id="{{ object.id }}">Double Vote - I Really Want This Too - &euro; 8.00</button>
			{% endif %}
		{% endif %}
	</div>

	<!-- comments segment -->
	<div class="ui container">

		<!-- divider -->
		<h3 id="number-of-comments" class="ui container horizontal divider header mt6 mb4">
			<i class="comment icon"></i> Comments 0
		</h3>

		<!-- reply form -->
		<div id="comment-reply-form">
			<form id="comment-reply-form" class="all-forms">

				<!-- characters left visual -->
				<label class="pl0 fwsemibold" for="comment-reply">
					<i class="paper plane icon"></i> Leave a Reply. <span class="pl2">Characters Left: <span id="comment-characters-left">500</span></span>
				</label>

				<!-- reply textarea -->
				<textarea class="mv1" id="comment-reply" rows="4" maxlength="500" required></textarea>
				<button class="ui button submit black">Post Comment</button>
			</form>
		</div>

		<!-- comments container -->
		<div id="comments" class="mv4">
			<div id="comments-container" class="ui comments"></div>

			<!-- empty comments container-->
			<div id="no-comments" class="ui placeholder pv6 tac segment">
				<div class="ui icon header">
					<i class="frown icon"></i>
					We don't have any Comments for this Ticket
				</div>
			</div>
		</div>

		<!-- end of comments tag-line -->
		<div id="end-of-comments" class="ui container horizontal divider header">
		  <i class="meh icon"></i> Looks like you've reached the end
		</div>
	</div>

	<!-- include errors / delete modal -->
	{% include 'tickets/partials/ticket-delete-item.html' %}
	{% include 'tickets/partials/ticket-error-occurred.html' %}
{% endblock %}

{% block javascript %}
	<script src="{%  static 'tickets/js/ticket-api.js' %}"></script>
	<script src="{%  static 'tickets/js/ticket-vote-api.js' %}"></script>
	<script src="{%  static 'comments/js/comment-api.js' %}"></script>
	<script src="{%  static 'cart/js/cart.js' %}"></script>
{% endblock %}

src/tickets/templates/tickets/ticket-list-view.html
{% extends '../base/base.html' %}
{% load static %}
{% block head_title %}{{ issue|title }}s{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'tickets/css/tickets.css' %}"/>{% endblock %}
{% block content %}

	<h1 class="callout" data-issue="{{ issue }}">{{ issue|title }}s</h1>
	<div class="ui container">

		<!-- top menu -->
		<div id="ticket-segment" class="ui top attached menu borderless stackable pv1">
			<div id="icon-bug" class="item">
				<i class="icon bug"></i>
			</div>

			<!-- right menu-->
			<div class="right item">

				<!-- search box -->
				<div class="ui action input">
					<input id="ticket-search-input" class="prompt" type="text" placeholder="Search {{ issue }}'s ..." pattern=".{4,}" required>
					<div id="ticket-search-btn" class="ui button" data-issue="{{ issue }}">Go</div>
				</div>
			</div>

			<!-- filter menu -->
			<div class="item responsive-padding">
				<div class="ui floating labeled icon dropdown button">
					<i class="filter icon"></i>
					<span class="text" id="ticket-order-by-default" data-order="-updated_on">Filter</span>
					<div class="menu" id="ticket-order-by" data-issue="{{ issue }}">
						<div class="item" data-order="-updated_on">Recently Updated</div>
						<div class="item" data-order="-created_on">Date Created</div>
						<div class="item" data-order="-votes">Most Popular</div>
						<div class="item" data-order="need help">Needs Help</div>
						<div class="item" data-order="in progress">In Progress</div>
						<div class="item" data-order="resolved">Resolved</div>
						{% if 'feature' in request.path %}
							<div class="item" data-order="-earned">Highest Earned</div>
						{% endif %}
					</div>
				</div>

				<!-- create new feature or bug button -->
				<div id="ticket-create-new-btn" class="ml1" >
					<a href="{% url 'tickets:ticket-create-view' issue=issue %}" class="ui button grey">Create New {{ issue|title }}</a>
				</div>
			</div>
		</div>

		<!-- bottom attached segment -->
		<div id="ticket-bottom-segment" class="ui bottom attached segment">
			<div><a id="reset-all-values" class="fr tar">reset all</a></div>

			<!-- loading animation -->
			{% include 'tickets/partials/ticket-empty-content.html' %}

			<!-- empty list container -->
			<div id="ticket-list-container">
				{% for object in object_list %}
					{% include 'tickets/partials/ticket-list-item.html' %}
				{% empty %}
					<li>No {{ issue|title }}'s yet.</li>
				{% endfor %}
			</div>
		</div>

		<!-- pagination buttons-->
		<div class="mt3">
			<div class="ui buttons right floated">
				<button id="previous-page" class="ui labeled icon button">
					<i class="left chevron icon"></i>
					Back
				</button>
				<button id="current-page" class="ui button disabled">1</button>
				<button id="next-page" class="ui right labeled icon button" data-count="{{ count }}">
					Forward
					<i class="right chevron icon"></i>
				</button>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script src="{% static 'tickets/js/ticket-api.js' %}"></script>
{% endblock %}